### PR TITLE
Make phy from tse bugfix

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hi,

here is the bugfix for `makePhyloseqFromTreeSummarizedExperiment`. 

Problem: `phyloseq` and `tree` objects require non-duplicated `rownames`; duplicated `rownames` lead to an error. 

Fix: If there are any duplicated `rownames` they are converted to unique names

Issue: https://github.com/microbiome/mia/issues/108

-Tuomas

### CODE REVIEW

**Review by FelixErnst — APPROVED** [review]
Can you merge it yourself?

**Comment by TuomasBorman** [comment]
Sure, do I have to do also version bump?

**Comment by FelixErnst** [comment]
Hi @TuomasBorman

please squash and merge next time. This makes charry picking easier to transfer commits to release.

**Comment by TuomasBorman** [comment]
Hi, ok, I wasn't aware of that but I keep that in my mind in the future

**Pull request merged**
