### PR TITLE
Skip failed test due to absence of dependency package

### PR DESCRIPTION
**Pull request by 0xMuluh**
🐛 Fix test run to avoid failed unit test as a result of dependency package not installed.
         - Before, unit test fails when dependency package is not installed
         - now, unit test skips if dependency package is not installed
       Fix typo in unit test file.

### CODE REVIEW

**Comment by antagomir** [comment]
Thanks for the suggestion.

However, I am not sure if skipping tests in such situation is a desired solution, if the alternative is to install the dependencies. In the end we would like to catch all problems that can be solved.

It is in general good practice to open an [issue](https://github.com/microbiome/mia/issues) first to receive feedback on the proposed solution, before preparing PR.

**Comment by TuomasBorman** [comment]
That was my suggestion. We already have this kind of thing implemented when miaTime is not installed. These packages are not required by mia (they are only required by certain functions), so they are not installed by default.

You have a point; tests should test all functions; dependency issues of tests should not occur for ordinary user

--> So I guess, we should also remove skipping of tests that require miaTime?

**Comment by antagomir** [comment]
Right, interesting point. I see pros & cons. The miaTime package is not in Bioconductor so it is more experimental. It might be justified to skip such dependencies in unit tests as a special case. Perhaps that is ok if it does not concern the core functionality of the package?

**Comment by 0xMuluh** [comment]
Thank you for the feedback. I'm not quite sure but I was thinking the same thing, because the miaTime, phyloseq, and biomformat do not concern the core functionallity of the package. what do you suggest I do?

**Comment by antagomir** [comment]
I think this good. Apologies for the delay, I had somehow not noticed this PR. Let us wait for the automated checks to pass.

**Comment by antagomir** [comment]
I accidentally closed and reopened again..

**Comment by 0xMuluh** [comment]
oh yes. I see, a failed check.

**Comment by antagomir** [comment]
@Daenarys8 do you need support in solving this?

**Comment by 0xMuluh** [comment]
I'm not sure but I  will take a look right away.  Apologies for the late reply

**Comment by antagomir** [comment]
Still fail. Ask when support needed.

**Comment by 0xMuluh** [comment]
> Still fail. Ask when support needed.

Yes please.  I need help.  I checked the changes I made and have not seen what could cause the failed check.  It fails test actually with 24 failed test.  The irony is locally,  the unittest run fine.  I'm thinking it has something to do with some omitted packages( skip_if_not_installed(********) and skip_if_not(require(*********)) but I'm not quite sure.

**Review by TuomasBorman — APPROVED** [review]

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
Awesome, PR merged!

**Pull request merged**
