### PR TITLE
Added rank to agglomerated rownames

### LINKED ISSUE #120: Naming and subsetting in agglomerations (and elsewhere?)
The naming in the output of `agglomerateByRank` is not necessarily as consistent as it could be.

Problem: the examples below show differences in `rownames()` for agglomerated `TreeSE` objects, and the name format varies by agglomeration arguments. This is important because rownames can be used subsetting, for instance by using functions such as `getPrevalentTaxa` (see below). Such operations run smoothly only when the same naming formats are being used.

Possible solution: in some cases, it is difficult/impossible to avoid adding the rank name (like "Genus::Dialister"); should we consider providing rownames always in this format? In addition, there could be a wrapper that allows an easy incorporation of shorter name formats as additional columns in `rowData`. Another option is to keep everything "as is" and trust that the user can clean up names whenever needed. But this will cause extra overheads for many users.

```
library(mia)
data(GlobalPatterns)

tseA <- agglomerateByRank(GlobalPatterns, rank="Genus")
print(rownames(tseA[1:3,]))

```
[1] "Class:Thermoprotei" "Genus:Sulfolobus"   "Class:Sd-NA"  

```
tseB <- agglomerateByRank(GlobalPatterns, rank="Genus", na.rm=TRUE)
print(rownames(tseB[1:3,]))

```
[1] "Sulfolobus"     "Cenarchaeum"    "Nitrosopumilus"

```
tseC <- agglomerateByRank(GlobalPatterns, rank="Genus", agglomerateTree=TRUE)
print(rownames(tseC[1:3,]))

```
[1] "Class:Thermoprotei" "Genus:Sulfolobus"   "Class:Sd-NA"

For instance, getPrevalentTaxa returns the names in the following format and one motivation has been that this could then be used for easy subsetting.

```
  prevalent <- getPrevalentTaxa(tse,                  
                                   rank = "Phylum",
                                   detection = 10,
                                   prevalence = 50/100,
                                   as_relative = FALSE)
     head(prevalent)

```  
[1] "Crenarchaeota"  "Euryarchaeota"  "Actinobacteria" "Spirochaetes"  
[5] "Proteobacteria" "Fusobacteria"

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hi,

now rank is added to rownames every time when data is agglomerated, e.g., "Thermoprotei" --> "Class:Thermoprotei"

Issue: https://github.com/microbiome/mia/issues/120

-Tuomas

### CODE REVIEW

**Review by antagomir — COMMENTED** [review]
I would then also include an @example of shortening the names.

**Comment by FelixErnst** [comment]
I think this is a solution for a non-issue (see comment on the issue). IMO a sharping of the example might be better.

**Comment by antagomir** [comment]
ok

**Comment by FelixErnst** [comment]
@TuomasBorman do you want to close this?

**Comment by TuomasBorman** [comment]
This PR includes example of adding prefixes. If that is not necessary (everything is ok to me), then this can be closed

**Comment by antagomir** [comment]
Let's merge and close.

**Pull request merged**
