### PR TITLE
Fix rworkflow

### PR DESCRIPTION
**Pull request by 0xMuluh**
This commit provides a temporal fix to rworkflow by bumping the r version of MacOS and Ubuntu and
fixing roxygen bug

### CODE REVIEW

**Comment by TuomasBorman** [comment]
https://github.com/microbiome/mia/pull/540

**Comment by TuomasBorman** [comment]
There are more issues related to roxygen and itemize (see the workflow)

**Comment by 0xMuluh** [comment]
all roxygen related warnings are resolved now.

**Comment by TuomasBorman** [comment]
rworkflow of miaViz is going through https://github.com/microbiome/miaViz/pull/124. It does not have any secrets. Make mia's rworkflow similar to it.

**Comment by TuomasBorman** [comment]
> rworkflow of miaViz is going through [microbiome/miaViz#124](https://github.com/microbiome/miaViz/pull/124). It does not have any secrets. Make mia's rworkflow similar to it.

Tested here https://github.com/microbiome/mia/pull/550

**Pull request merged**
