### PR TITLE
Unify parameter description

### PR DESCRIPTION
**Pull request by 0xMuluh**
1- We have used @inheritParams to harmonize parameter desc. 
Mentioning issue #458  and #372

TODO: harmonize parameter naming with dot naming(e.g on.rank.only)

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Very nice, seems to work. However, let's first 

1. check what parameters we have

2. Determine parameter names and descriptions

3. Modify documents and use inheritParam

**Comment by antagomir** [comment]
Could we finalize this and then merge asap?

**Review by antagomir — APPROVED** [review]

**Comment by antagomir** [comment]
@Daenarys8 this seems to be out of sync?

**Comment by TuomasBorman** [comment]
This probably requires new PR since "everything" has changed. This has been in a plan of July

**Comment by TuomasBorman** [comment]
Closing, let's implement new PR soon

**Pull request closed without merging**
