### PR TITLE
Subsample counts fix

### PR DESCRIPTION
**Pull request by TuomasBorman**
Hi,

I found a bug.

`subsampleCounts` led to an error, when there were no samples after subsampling. 

```
library(mia)
data(GlobalPatterns)

tse.subsampled <- subsampleCounts(GlobalPatterns, 
                                  min_size = 6000000, 
                                  name = "subsampled",
                                  replace = TRUE,
                                  seed = 1938)

```

-Tuomas

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Now this returns `NULL` and message, if there are no samples

**Review by antagomir — APPROVED** [review]
Seems like a good solution.

**Review by microsud — APPROVED** [review]
Good catch

**Comment by FelixErnst** [comment]
The solution was a bit to much window dressing for my taste. Again the fix was 15 lines away from the cause. This is now rectified and it errors in this case.

Reporting `NULL` would mean a difference in input and output type, which is not expected I would argue, therefore the error. An another option would be just report an `SE` without any columns and let the use figure it out for themselves.

**Review by FelixErnst — APPROVED** [review]

**Review by antagomir — APPROVED** [review]

**Pull request merged**
