### PR TITLE
Temporal fix for rworkflow bug

### PR DESCRIPTION
**Pull request by 0xMuluh**
This commit provides a temporal fix to rworkflow by bumping the r version of MacOS and Ubuntu and
fixing a  bug in R/estimateDiversity.R.

### CODE REVIEW

**Comment by 0xMuluh** [comment]
Bumping r version for Mac workflow tends to work. I think the same for Ubuntu at least, until the fix in 
R/estimateDiversity.R is merged.

**Comment by TuomasBorman** [comment]
Alright, maybe we could go like this as a temporary fix. Can you fix estimateDiversity.R in this PR (change the title also according to that)

**Comment by TuomasBorman** [comment]
Roxygen2 changed how list is created. It seems that it throws now a warning. This is related to this issue: https://github.com/microbiome/mia/issues/532

Check the workflow run, you will see these warnings:
```

 Warning in readLines(conn, line - oldline, warn = FALSE) :
    invalid input found on input connection './man/estimateDominance.Rd'
  checkRd: (-1) estimateDominance.Rd:99-101: Lost braces in \itemize; meant \describe ?
```

Can you fix them?

See for example from [here](https://github.com/EBI-Metagenomics/HoloFoodR/blob/devel/R/getResult.R) how lists are now created

**Comment by 0xMuluh** [comment]
@TuomasBorman I think we can finalize this now. Unless, you have more changes in mind

**Comment by TuomasBorman** [comment]
Looks good, but still not working. Update manual pages, let's see if that works

**Comment by 0xMuluh** [comment]
I updated man pages already. The fail is as at the stage of deployment. Something about the bot not having permission to deploy to the repo.  See log [here](https://github.com/microbiome/mia/actions/runs/9059118621/job/24886047784?pr=540#step:4:5706)

**Comment by TuomasBorman** [comment]
Now there is another error. Can you remove the rworkflows file and then create a new one with rworkflows::use_workflow(). That should update the workflow. Remember to specify R version to 4.4.0 (auto seems not to work)

In the future, create branch directly to mia. It is simpler since then I can also contribute much easier.

**Comment by TuomasBorman** [comment]
https://github.com/neurogenomics/rworkflows/issues/130

Try to put R back to auto. It should work

**Comment by TuomasBorman** [comment]
From the rworkflows issue

> One thing that might help is removing the ubuntu-latest rspm line, or replacing it with rspm: ~

Can you try that fix?

**Comment by 0xMuluh** [comment]
> From the rworkflows issue
> 
> > One thing that might help is removing the ubuntu-latest rspm line, or replacing it with rspm: ~
> 
> Can you try that fix?

Yeah, I tried this. Still failing. I think the issue here is permission to microbiome/mia.git is denied to github-actions[bot]. I'm not quite sure but did we alter the secrets?

**Comment by TuomasBorman** [comment]
> > From the rworkflows issue
> > > One thing that might help is removing the ubuntu-latest rspm line, or replacing it with rspm: ~
> > 
> > 
> > Can you try that fix?
> 
> Yeah, I tried this. Still failing. I think the issue here is permission to microbiome/mia.git is denied to github-actions[bot]. I'm not quite sure but did we alter the secrets?

Yes, I noticed that too. However, nothing should have changed. I will check

**Pull request merged**
