### PR TITLE
altExp support for meltAssay 

### PR DESCRIPTION
**Pull request by ake123**
altExp support for meltAssay #343

### CODE REVIEW

**Comment by antagomir** [comment]
Remember to:
- upgrade version number in DESCRIPTION
- update NEWS file
-  squash and merge if ready

**Comment by ake123** [comment]
Is the version other than 1.9.9 ?

**Comment by antagomir** [comment]
The DESCRIPTION file in master/main branch gives the latest version (it is indeed 1.9.9). 

The numbering goes in numeric order so the next minor update is 1.9.10 etc.

**Comment by antagomir** [comment]
I add this now anyway. Not so critical here.

**Pull request merged**
