### PR TITLE
Streamline RDA significance attribute

### PR DESCRIPTION
**Pull request by RiboRings**
Hi! I tried to streamline `attr(rda, "significance")` so that output is easier to interpret and use. Also added Total and Explained variance columns to permanova table.

For example:

```
library(mia)

# Load data
data(enterotype, package="mia")
tse <- enterotype

# Apply relative transform
tse <- transformCounts(tse, method = "relabundance")

# # Perform RDA
mae <- runRDA(tse,
              assay.type = "relabundance",
              formula = assay ~ ClinicalStatus + Gender + Age,
              distance = "bray",
              na.action = na.exclude)

rda_tse <- mae[["subset"]]
rdrda <- reducedDim(rda_tse, "RDA")

attr(rdrda, "significance")

# $permanova
#
#                Df SumOfSqs     F Pr(>F) Total variance Explained variance
# Model           6   1.1157 1.940  0.040          3.991            0.27952
# ClinicalStatus  4   0.5837 1.522  0.129          3.991            0.14625
# Gender          1   0.1679 1.751  0.100          3.991            0.04206
# Age             1   0.5245 5.471  0.001          3.991            0.13140
# Residual       30   2.8757    NA     NA          3.991            0.72048
#
# $homogeneity
#
#                Df  Sum Sq Mean Sq F value    Pr(>F)
# ClinicalStatus  4 0.25108 0.06277  2.7440 0.0442777
# Gender          1 0.01032 0.01032  0.4158 0.5229990
# Age            29 0.32723 0.01128 17.0255 0.0003692
```

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Thanks! This output looks very neat. I was wondering if the dropped calculation info includes important information. For example, they include the formula that is used to calculate these

Hmm..., maybe we could have a hidden parameter for full data and this kind of summary table...

**Comment by RiboRings** [comment]
Here's the previous output for the same code above. I felt like it was too long and information gets too diluted.

```
attr(,"significance")
attr(,"significance")$summary
               Df (PERMANOVA) SumOfSqs (PERMANOVA) F (PERMANOVA) Pr(>F) (PERMANOVA) Df (homogeneity)
Age                         1               0.5245         5.471              0.001               29
ClinicalStatus              4               0.5837         1.522              0.136                4
Gender                      1               0.1679         1.751              0.110                1
Model                       6               1.1157         1.940              0.036               NA
Residual                   30               2.8757            NA                 NA               NA
               Sum Sq (homogeneity) Mean Sq (homogeneity) F value (homogeneity) Pr(>F) (homogeneity)
Age                         0.32723               0.01128               17.0255            0.0003692
ClinicalStatus              0.25108               0.06277                2.7440            0.0442777
Gender                      0.01032               0.01032                0.4158            0.5229990
Model                            NA                    NA                    NA                   NA
Residual                         NA                    NA                    NA                   NA

attr(,"significance")$permanova
attr(,"significance")$permanova$model
Permutation test for dbrda under reduced model
Permutation: free
Number of permutations: 999

Model: vegan::dbrda(formula = assay ~ ClinicalStatus + Gender + Age, data = variables, distance = "bray", na.action = ..2)
         Df SumOfSqs    F Pr(>F)  
Model     6     1.12 1.94  0.036 *
Residual 30     2.88              
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

attr(,"significance")$permanova$variables
Permutation test for dbrda under reduced model
Marginal effects of terms
Permutation: free
Number of permutations: 999

Model: vegan::dbrda(formula = assay ~ ClinicalStatus + Gender + Age, data = variables, distance = "bray", na.action = ..2)
               Df SumOfSqs    F Pr(>F)    
ClinicalStatus  4    0.584 1.52  0.136    
Gender          1    0.168 1.75  0.110    
Age             1    0.524 5.47  0.001 ***
Residual       30    2.876                
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


attr(,"significance")$homogeneity
attr(,"significance")$homogeneity$ClinicalStatus
attr(,"significance")$homogeneity$ClinicalStatus$betadisper

	Homogeneity of multivariate dispersions

Call: betadisper(d = dist_mat, group = var)

No. of Positive Eigenvalues: 24
No. of Negative Eigenvalues: 14

Average distance to median:
     CD elderly healthy   obese      UC 
  0.000   0.216   0.318   0.201   0.000 

Eigenvalues for PCoA axes:
(Showing 8 of 38 eigenvalues)
PCoA1 PCoA2 PCoA3 PCoA4 PCoA5 PCoA6 PCoA7 PCoA8 
1.352 1.041 0.431 0.351 0.227 0.181 0.145 0.124 

attr(,"significance")$homogeneity$ClinicalStatus$anova
Analysis of Variance Table

Response: Distances
          Df Sum Sq Mean Sq F value Pr(>F)  
Groups     4  0.251  0.0628    2.74  0.044 *
Residuals 34  0.778  0.0229                 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


attr(,"significance")$homogeneity$Gender
attr(,"significance")$homogeneity$Gender$betadisper

	Homogeneity of multivariate dispersions

Call: betadisper(d = dist_mat, group = var)

No. of Positive Eigenvalues: 24
No. of Negative Eigenvalues: 14

Average distance to median:
    F     M 
0.270 0.302 

Eigenvalues for PCoA axes:
(Showing 8 of 38 eigenvalues)
PCoA1 PCoA2 PCoA3 PCoA4 PCoA5 PCoA6 PCoA7 PCoA8 
1.352 1.041 0.431 0.351 0.227 0.181 0.145 0.124 

attr(,"significance")$homogeneity$Gender$anova
Analysis of Variance Table

Response: Distances
          Df Sum Sq Mean Sq F value Pr(>F)
Groups     1  0.010  0.0103    0.42   0.52
Residuals 37  0.918  0.0248               


attr(,"significance")$homogeneity$Age
attr(,"significance")$homogeneity$Age$betadisper

	Homogeneity of multivariate dispersions

Call: betadisper(d = dist_mat, group = var)

No. of Positive Eigenvalues: 23
No. of Negative Eigenvalues: 13

Average distance to median:
 0.25  0.33   0.5  0.58   1.5     3    24    25    28    30    35    36    37    38    45    47    49    54 
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.194 0.000 0.000 0.000 0.289 0.000 0.000 0.000 0.231 0.000 
   59    60    61    62    63    64    70    72    77    80    85    87 
0.147 0.137 0.000 0.000 0.130 0.000 0.000 0.000 0.000 0.000 0.000 0.000 

Eigenvalues for PCoA axes:
(Showing 8 of 36 eigenvalues)
PCoA1 PCoA2 PCoA3 PCoA4 PCoA5 PCoA6 PCoA7 PCoA8 
1.329 1.038 0.417 0.324 0.215 0.169 0.141 0.118 

attr(,"significance")$homogeneity$Age$anova
Analysis of Variance Table

Response: Distances
          Df Sum Sq Mean Sq F value  Pr(>F)    
Groups    29  0.327 0.01128      17 0.00037 ***
Residuals  7  0.005 0.00066                    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

**Comment by RiboRings** [comment]
I think having the model metadata as a hidden parameter/attribute is a good idea. How do you do it in practice?

**Comment by antagomir** [comment]
The function should return same type imo. i.e. TreeSE should not become MAE, is this possible to avoid?

**Comment by TuomasBorman** [comment]
> I think having the model metadata as a hidden parameter/attribute is a good idea. How do you do it in practice?

with `...` parameter



> The function should return same type imo. i.e. TreeSE should not become MAE, is this possible to avoid?

It is possible to avoid, but then the data is subsetted and includes only subset of samples. (If certain sample does not include metadata, it is dropped)

**Comment by antagomir** [comment]
Example on the model data is then important, to show how to do.

If we cannot reasonably avoid returning MAE from TreeSE function (`runRDA`) then the logic of this should be explained very clearly in the function manpage and perhaps elsewhere (vignette, OMA..) but however avoiding duplication. 

Just to be explicit: do I understand correctly that MAE is used here because:
- covariate data ("metadata" / "colData") is not necessarily available for all samples
-> need to subset to those samples where this is available
-> RDA is run on a subset of the samples to get reducedDim
-> we want to store the exact data for which the RDA was run

Or did I misunderstand this in a hurry?

Why don't we just use the reducedDim slot to represent the reduced dimensional data?

**Comment by TuomasBorman** [comment]
> 

Correct.

In reducedDim, rows corresponds the columns in TreeSE object, i.e. samples. These samples must match. Because some samples are dropped in reducedDim, they do not match anymore

**Comment by antagomir** [comment]
Right.. then I am still wondering if adding MAE really is the ideal solution. It adds a new level of complexity, for which new set of tools (visualization etc) are possibly needed.

Other, simpler options could be:

- show how to subset the data correctly for RDA analysis or use imputation, then just run RDA without need to use the complex MAE thing; this will also educate users to use RDA correctly when shown well in examples. The function can include informative error for cases with missing values and ask the user to remove (or impute) missing values before analysis

or

- do the subsetting for the user as done now but just return the reduced dim directly, and allow user to choose if they like to operate on it directly or add in MAE somehow. In that case would be necessary to show how to do the downstream analyses based on such output-

**Review by antagomir — CHANGES_REQUESTED** [review]
See discussion.

**Comment by RiboRings** [comment]
The first option is probably more consistent with all other `run` functions

**Comment by antagomir** [comment]
Using the first option would educate the users, and also help to avoid quite much complexity in the solution. Shall we go with that?

**Comment by TuomasBorman** [comment]
First option might be too complicated  compared to just returning the subsetted object. In addition, vegan::rda includes multiple choices for handling NA values.

```
variables <- c(1, 2, 3)
samples <- rowSums( colData(tse)[, variables]) == length(variables)
tse <- tse[, samples]
runRDA(tse)
```
Compared to if we just return the subsetted TreeSE and give a warning ("All samples did not have sufficient metadata. Subsetted")
```
runRDA(tse)
```

These above do basically the same thing but the latter is much easier for user and does not require additional (annoying) manipulation.

The MAE solution was just because I was wondering whether it is ok to lose the original data while doing RDA (some samples are removed). 

Also , I'm wondering if NA values are ok in RDA ordination? --> meaning that if we

1 RUn RDA analysis and get the subsetted RDA object as result
2. Add NA values for those samples that do not have data
3. Add whole RDA ordination with NA values to original object

**Comment by TuomasBorman** [comment]
> First option might be too complicated compared to just returning the subsetted object. In addition, vegan::rda includes multiple choices for handling NA values.
> 
> ```
> variables <- c(1, 2, 3)
> samples <- rowSums( colData(tse)[, variables]) == length(variables)
> tse <- tse[, samples]
> runRDA(tse)
> ```
> 
> Compared to if we just return the subsetted TreeSE and give a warning ("All samples did not have sufficient metadata. Subsetted")
> 
> ```
> runRDA(tse)
> ```
> 
> These above do basically the same thing but the latter is much easier for user and does not require additional (annoying) manipulation.
> 
> The MAE solution was just because I was wondering whether it is ok to lose the original data while doing RDA (some samples are removed).
> 
> Also , I'm wondering if NA values are ok in RDA ordination? --> meaning that if we
> 
> 1 RUn RDA analysis and get the subsetted RDA object as result 2. Add NA values for those samples that do not have data 3. Add whole RDA ordination with NA values to original object

This seems to work. No need to subset or creating MAE. Just add NA values to those samples that are not present https://github.com/microbiome/mia/pull/381

**Review by TuomasBorman — APPROVED** [review]

**Comment by antagomir** [comment]
Ok that sounds good.

**Comment by antagomir** [comment]
Just ensure that OMA is also updated as appropriate (no need copypaste all examples there but at least remove outdated content)

**Pull request merged**
