### PR TITLE
Featurebranch

### PR DESCRIPTION
**Pull request by shigdel**

### CODE REVIEW

**Review by antagomir — CHANGES_REQUESTED** [review]
Thanks!

The PR is correctly done.

You can see at the Pull requests tab that the checks have failed.

In order to work through that, we need to make sure that you are able to run tests successfully at your end.

Can you do the following, and troubleshoot (with our online support) if you bump into errors or other problems:

1. If you can, always pull the latest changes from microbiome/mia master branch (probably not critical for this PR but good practice; can be omitted). This ensures that your version is in sync with the release version.
2. Make sure documentation is up-to-date by running `devtools::document()` on the package
2. Check that the examples run through: `devtools::run_examples()`
3. Check that the tests pass: `devtools::test()`
4. Check that checks pass: `devtools::check()`
5. Check that Bioconductor checks pass: `BiocCheck::BiocCheck()`
6. I think we would need to include deprecation message; for an example, see how it was added to `calculateDistances` by @TuomasBorman

**Comment by FelixErnst** [comment]
This is currently not working, is it? Do you want to fix this PR @shigdel ? @antagomir ?

**Comment by antagomir** [comment]
Thanks - this seems to have been left hanging around. 

The following needs to be done:

1) pull the latest changes from master branch to the featurebranch

2) fix possible conflicts

3) add the requested updates

4) push the updated version to featurebranch

Then we can see if the checks go through and this PR can be considered ready. 

@shigdel can you do this?

**Comment by FelixErnst** [comment]
Also add information to NEWS

**Comment by FelixErnst** [comment]
Duplicate of #153 

Closing this

**Pull request closed without merging**
