### PR TITLE
Fixing Wrong deprecation message 

### PR DESCRIPTION
**Pull request by ake123**
Fixed Wrong deprecation message with mergeFeatures (#416) and mergeFeaturesByRank

### CODE REVIEW

**Comment by antagomir** [comment]
checks fail?

**Comment by ake123** [comment]
Shows no error but it still fails
```r
0 errors ✔ | 1 warning ✖ | 2 notes ✖
Error: R CMD check found WARNINGs
Execution halted
Error: Process completed with exit code 1.
```

**Comment by antagomir** [comment]
>  Warning: 'agglomerateByRank' is deprecated.

-> is this still used in examples / vignettes / tests?

warnings also lead to failure

**Comment by ake123** [comment]
It is not being used in  examples / vignettes / tests. Checked ` R CMD check mia_1.9.11.tar.gz` to see the checkl.og and here is the error.
```r
* using log directory ‘/Users/akasia/mia.Rcheck’
* using R version 4.3.1 (2023-06-16)
* using platform: x86_64-apple-darwin20 (64-bit)
* R was compiled by
    Apple clang version 14.0.3 (clang-1403.0.22.14.1)
    GNU Fortran (GCC) 12.2.0
* running under: macOS Ventura 13.5
* using session charset: UTF-8
* checking for file ‘mia/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘mia’ version ‘1.9.11’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Packages suggested but not available: 'dada2', 'reldist'

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE
Status: 1 ERROR

```

**Comment by antagomir** [comment]
The missing packages should install automatically during the GHA workflow if they are listed in the DESCRIPTION file. If not, one reason could be difference in the R version and Bioconductor version (latter usually relies on certain R version, and we use Bioc devel in general). The GHA workflow can be used to install packages as well but should not, in general, be used for packages that should already install via DESCRIPTION.. ping if more guidance is necessary..

**Review by TuomasBorman — CHANGES_REQUESTED** [review]
Looks good but there are some additional files (.DS_Store). Remove those

**Comment by antagomir** [comment]
up

**Comment by ake123** [comment]
> Looks good but there are some additional files (.DS_Store). Remove those

removed the additional files

**Pull request closed without merging**
