### PR TITLE
Issue127

### LINKED ISSUE #127: Function naming
I noticed that we refer to unifrac with UniFrac (e.g. in `calculateUniFrac`).

The original authors and QIIME2 seem to use name "Unifrac" with no uppercase F. 

Perhaps a minor detail but I would prefer changing this to the standard spelling. 

If @FelixErnst agrees, @shigdel could make a PR on this.

### PR DESCRIPTION
**Pull request by shigdel**
renaming UniFrac  to unifrac , calculateUnifrac to calculateunifrac

### CODE REVIEW

**Review by antagomir — COMMENTED** [review]
There seems to be some Git conflicts that need to be resolved. Pull the latest version from master branch, resolve possible conflicts, and add to the PR.
 
The file name could be changed as well before merging?

**Comment by shigdel** [comment]
i sent a pull request from the forked one that i had done earlier but i dont have a permission to send PR  to the  mia (master)

**Comment by antagomir** [comment]
> i sent a pull request from the forked one that i had done earlier but i dont have a permission to send PR to the mia (master)

You have done a PR from `shigdel:issue127` to `microbiome:master` for the *mia* repository i.e. you are already sending PR to mia/master branch in this current PR.

If you want to update the PR, then you can push new changes to shigdel:issue127 and they will become part of this PR automatically.

If you want to sync with the master, you will need to update your fork or branch. You can do this for instance on command line with 

`git remote add upstream git@github.com:microbiome/mia.git`

Then you can get the latest changes with:
```
git fetch upstream
git merge upstream/master
```

Then resolve conflicts if there are any, and commit your own changes to shigdel:issue127 as usual. Then the two repositories should be in sync and shigdel:issue127 has your own new changes added in the PR

If you wait too long with the PR, the mia/master will evolve and your branch will gradually get out of sync. This is the way to synchornize it.

**Comment by shigdel** [comment]
Thanks for explaining i will try it

**Pull request closed without merging**
