### PR TITLE
Fix loadFromBiom: prefix match

### PR DESCRIPTION
**Pull request by TuomasBorman**

### CODE REVIEW

**Comment by TuomasBorman** [comment]
Previously, "k__" matched also with "sk__" prefix that can be found from biom files. This is now fixed

I will update version and news, if this is ok

**Comment by antagomir** [comment]
Does "sk__" have a meaning, or is it a typo?

**Comment by TuomasBorman** [comment]
I guess it is in Biom files to denote upper class compared to Kingdom. One dataset had mitochondria which broke the import because we have not taken this "sk" class into account

**Comment by antagomir** [comment]
Ok from my side. Just thinking if we should handle those special cases somehow.

**Comment by TuomasBorman** [comment]
This affects only renaming of rowData columns.

1. User can specify whether he/she wants to rename columns
2. Columns are renamed based on match, e.g., "k__" --> "Kingdom"
3. If column is not matched, the column name is unchanged

We had discussion with Felix about TAXONOMY_RANKS in mia. --> we decided to include only "real" taxonomy ranks (ASV and OTU was not added). I think this is little bit similar situation.

**Comment by antagomir** [comment]
Yes, good.

**Comment by antagomir** [comment]
Status of this? Seems related to the discussion in the Tengeler data set PR data import part.

**Comment by TuomasBorman** [comment]
This is good, I will update the branch

This is not directly related to Tengeler data PR --> there is something else happening

**Comment by antagomir** [comment]
To be closed when possible, ideal to not have too many open PRs simultaneously.

**Comment by antagomir** [comment]
Status of this?

**Comment by TuomasBorman** [comment]
This is good to go

**Comment by antagomir** [comment]
Ok. It is most clear if the initiator of the PR can close it. This way we can avoid premature closings. 

Confirm by closing the issue.

**Pull request merged**
